name: Github Maven Repository Upload
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    name: Github Maven Repository Upload
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: maven-settings-xml-action
        uses: whelk-io/maven-settings-xml-action@v14
        with:
          repositories: '[{ "id": "github", "url": "https://maven.pkg.github.com/openlena/*", "snapshots": { "enabled": "true" } }]'
          servers: ${{secrets.GH_MVN_REPO_USER_INFO}}
      - name: check settings.xml
        run: cat ~/.m2/settings.xml
      - name: Packaging with Maven
        run: mvn -B package
#      - uses: actions/delete-package-versions@v1
#        continue-on-error: true
#        with:
#          owner: 'openlena'
#          repo: 'lena-ctl'
#          package-name: 'io.openlena.lena-ctl'
#          token: ${{ secrets.GH_MVN_REPO_PAT }}
      - name: Deploy with Maven
        run: mvn -B deploy